export const SET_CATEGORY = "SET_CATEGORY";

export const QUIZ_DATA_LOADING = "QUIZ_DATA_LOADING";
export const SAVE_QUIZ_DATA = "SAVE_QUIZ_DATA";
export const QUIZ_DATA_ERROR = "QUIZ_DATA_ERROR";
export const GAME_LOADING = "GAME_LOADING";
export const SAVE_QUESTIONS = "SAVE_QUESTIONS";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
export const SET_SELECTED_OPTIONS = "SET_SELECTED_OPTIONS";
export const GAME_ERROR = "GAME_ERROR";
export const RESET_QUIZ = "RESET_QUIZ";
